In [1]:
import pandas as pd
import numpy as np

In [2]:
dupDf = pd.read_csv('../csv/dupDf.csv', encoding='utf-8')

In [3]:
dupDf.head()

,Unnamed: 0,tracking_id,date,status,mapped_status,provider,day,month
0,696119,1882077,2018-04-30 07:14:00,Řádně podaná zásilka - do rozhodné doby,Převzato dopravcem,ČESKÁ POŠTA,30,4
1,696118,1882076,2018-04-30 06:52:00,Pořízeno na pochůzku,Na cestě k příjemci,ČESKÁ POŠTA,30,4
2,696115,1882075,2018-04-30 06:52:00,Uloženo na poště,Na cestě k příjemci,ČESKÁ POŠTA,30,4
3,696116,1882075,2018-04-30 06:58:00,Uloženo na poště,Na cestě k příjemci,ČESKÁ POŠTA,30,4
4,696117,1882075,2018-04-30 07:14:00,Řádně podaná zásilka - do rozhodné doby,Převzato dopravcem,ČESKÁ POŠTA,30,4

<h2>Mazanie stĺpcov</h2>

In [4]:
del dupDf["Unnamed: 0"]

In [5]:
dupDf.head()

,tracking_id,date,status,mapped_status,provider,day,month
0,1882077,2018-04-30 07:14:00,Řádně podaná zásilka - do rozhodné doby,Převzato dopravcem,ČESKÁ POŠTA,30,4
1,1882076,2018-04-30 06:52:00,Pořízeno na pochůzku,Na cestě k příjemci,ČESKÁ POŠTA,30,4
2,1882075,2018-04-30 06:52:00,Uloženo na poště,Na cestě k příjemci,ČESKÁ POŠTA,30,4
3,1882075,2018-04-30 06:58:00,Uloženo na poště,Na cestě k příjemci,ČESKÁ POŠTA,30,4
4,1882075,2018-04-30 07:14:00,Řádně podaná zásilka - do rozhodné doby,Převzato dopravcem,ČESKÁ POŠTA,30,4

<h2>Zgrupovanie a agregácia dát</h2>

<p>Keď už vieme, ako dáta</p>
<ul>
    <li>radiť</li>
    <li>triediť</li>
    <li>vyhľadávať na základe nejakej podmienky</li>
</ul>

<p>je niekedy dobré vedieť dáta zgrupiť a zoskupiť pomocou viacerých kritérií. Agregácia a zgrupovanie dát, funguje na podobnom princípe ako pivotné tabuľky, s tým rozdielom, že pivotné tabuľky nám poskytujú viac možností a funkcionality. No pre jednoduché use casy, alebo rýchly pohľad na dáta, je agregácia a zgrupovanie tou vhodnou voľbou.</p>

In [6]:
dupDf.groupby('provider')

<p>Ako vidíme, návratovou hodnotnou nie je klasický DateFrame, aký poznáme, ale DataFrameGroupBy objekt. Na tento objekt sa pozeráme ako na dočasné view, pričom dáta sú zobrazené prostredníctvom prílušnej až agregačnej metódy alebo funkcie.</p>

In [7]:
dupDf.groupby('provider').head()

,tracking_id,date,status,mapped_status,provider,day,month
0,1882077,2018-04-30 07:14:00,Řádně podaná zásilka - do rozhodné doby,Převzato dopravcem,ČESKÁ POŠTA,30,4
1,1882076,2018-04-30 06:52:00,Pořízeno na pochůzku,Na cestě k příjemci,ČESKÁ POŠTA,30,4
2,1882075,2018-04-30 06:52:00,Uloženo na poště,Na cestě k příjemci,ČESKÁ POŠTA,30,4
3,1882075,2018-04-30 06:58:00,Uloženo na poště,Na cestě k příjemci,ČESKÁ POŠTA,30,4
4,1882075,2018-04-30 07:14:00,Řádně podaná zásilka - do rozhodné doby,Převzato dopravcem,ČESKÁ POŠTA,30,4
41,1881727,2018-04-30 05:41:02,Převážení/vážení,Převzato dopravcem,PPL,30,4
42,1881726,2018-04-30 05:41:01,Převážení/vážení,Převzato dopravcem,PPL,30,4
43,1881724,2018-04-30 05:41:02,Převážení/vážení,Převzato dopravcem,PPL,30,4
44,1881722,2018-04-30 05:41:02,Převážení/vážení,Převzato dopravcem,PPL,30,4
45,1881721,2018-04-30 05:41:04,Převážení/vážení,Převzato dopravcem,PPL,30,4
4056,1876214,2018-04-27 20:04:00,Příjem na depo,Převzato dopravcem,GEIS,27,4
4057,1876214,2018-04-27 20:12:42,Naložení na hb,Nezadane,GEIS,27,4
4058,1876214,2018-04-28 00:25:36,Příjem na depo,Převzato dopravcem,GEIS,28,4
4059,1876214,2018-04-28 03:47:33,Naložení na hb,Nezadane,GEIS,28,4
4060,1876214,2018-04-30 08:08:12,Příjem na depo,Převzato dopravcem,GEIS,30,4

In [8]:
dupDf.groupby('provider').count()

             tracking_id    date  status  mapped_status     day   month
provider
GEIS               32584   32584   32584          32584   32584   32584
PPL               520229  520229  520229         520229  520229  520229
ČESKÁ POŠTA       175891  175891  175891         175891  175891  175891

In [9]:
dupDf.groupby('mapped_status')["date"].min()

mapped_status
Doručeno               2018-03-01 06:10:04
Na cestě k příjemci    2018-03-01 00:02:00
Nezadane               2018-03-01 00:01:01
Převzato dopravcem     2018-03-01 00:06:43
Stornováno             2018-03-01 05:10:35
Name: date, dtype: object

<h2>Úlohy</h2>

<ul>
    <li>Z dátového setu <b>dupDf</b> vypíšte medián po provideroch za stĺpec <b>tracking_id</b>. Na výpočet mediánu sa používa funkcia <code>median()</code></li>
</ul>

In [10]:
dupDf.groupby('provider')['tracking_id'].median()

provider
GEIS           1783134
PPL            1762349
ČESKÁ POŠTA    1773401
Name: tracking_id, dtype: int64

In [11]:
dupDf.groupby(['provider', 'mapped_status'])['date'].min()

provider     mapped_status
GEIS         Doručeno               2018-03-01 08:04:26
             Na cestě k příjemci    2018-03-01 05:53:00
             Nezadane               2018-03-01 00:01:01
             Převzato dopravcem     2018-03-01 00:06:43
             Stornováno             2018-03-01 10:08:21
PPL          Doručeno               2018-03-01 06:10:04
             Na cestě k příjemci    2018-03-01 00:32:50
             Nezadane               2018-03-01 06:27:12
             Převzato dopravcem     2018-03-01 00:22:06
             Stornováno             2018-03-01 05:10:35
ČESKÁ POŠTA  Doručeno               2018-03-01 06:35:00
             Na cestě k příjemci    2018-03-01 00:02:00
             Nezadane               2018-03-01 02:42:00
             Převzato dopravcem     2018-03-01 06:45:00
             Stornováno             2018-03-01 05:51:00
Name: date, dtype: object

In [12]:
dupDf[dupDf['mapped_status'] == 'Stornováno'].groupby('provider')['tracking_id'].count()

provider
GEIS            199
PPL            2951
ČESKÁ POŠTA    2113
Name: tracking_id, dtype: int64

<h2>Rozdiel medzi count() a size()</h2>

<p>Hlavným rozdielom medzi <code>count()</code> a <code>size()</code> je v tom, že <code>size()</code> zahrňuje do výpočtu aj <b>NaN</b> hodnoty. Pritom návratovou hodnotou <code>size()</code> je Séria, pričom <code>count()</code> vracia Dataframe objekt.</p>

In [13]:
dupDf[dupDf['mapped_status'] == 'Stornováno'].groupby('provider').count()

             tracking_id  date  status  mapped_status   day  month
provider
GEIS                 199   199     199            199   199    199
PPL                 2951  2951    2951           2951  2951   2951
ČESKÁ POŠTA         2113  2113    2113           2113  2113   2113

In [14]:
dupDf[dupDf['mapped_status'] == 'Stornováno'].groupby('provider').size()

provider
GEIS            199
PPL            2951
ČESKÁ POŠTA    2113
dtype: int64

<h2>Describe()</h2>

<p>Funkcia <code>describe()</code> nám poskytuje v jednom čase viacero štatistických funkcií naraz. Taktiež si môžeme pri definícii vybrať, ktoré štatistické funkcie chceme použiť. Ak náš dátový set nie je tvorený iba číslami, výsledok môže vyzerať inak.</p>

In [15]:
dupDf[dupDf['mapped_status'] == 'Doručeno'].groupby('provider').date.describe()

              count unique                  top freq
provider
GEIS           5101   4356  2018-03-16 11:00:00    8
PPL          104156  95019  2018-04-24 11:20:28   39
ČESKÁ POŠTA   30583  16464  2018-04-10 15:36:00   11

In [16]:
dupDf[dupDf['mapped_status'] == 'Doručeno'].groupby('provider').day.describe()

                count       mean       std  min  25%   50%   75%   max
provider
GEIS           5101.0  15.392276  7.896240  1.0  9.0  16.0  22.0  30.0
PPL          104156.0  14.876474  7.984211  1.0  8.0  15.0  21.0  31.0
ČESKÁ POŠTA   30583.0  15.489978  8.108980  1.0  9.0  16.0  23.0  31.0

In [17]:
dupDf.describe()

        tracking_id            day          month
count  7.287040e+05  728704.000000  728704.000000
mean   1.766793e+06      14.955358       3.466530
std    5.633244e+04       8.124148       0.498879
min    1.415857e+06       1.000000       3.000000
25%    1.718272e+06       8.000000       3.000000
50%    1.764741e+06      15.000000       3.000000
75%    1.812285e+06      22.000000       4.000000
max    1.882077e+06      31.000000       4.000000

<h2>Úloha</h2>

<ul>
    <li>Použite funkciu <code>describe()</code> nad dátovým setom <b>dupDf</b>, kde zgrupíte dáta za providera nad stĺpcom mapped_status.</li>
</ul>

In [18]:
dupDf.groupby('provider').mapped_status.describe()

              count unique                  top    freq
provider
GEIS          32584      5   Převzato dopravcem   14947
PPL          520229      5  Na cestě k příjemci  237593
ČESKÁ POŠTA  175891      5  Na cestě k příjemci  114654

<h2>Agregačné funkcie</h2>

In [19]:
dupDf.groupby(['provider', 'mapped_status']).agg({'tracking_id':"count"})

                                 tracking_id
provider    mapped_status
GEIS        Doručeno                    5101
            Na cestě k příjemci         6186
            Nezadane                    6151
            Převzato dopravcem         14947
            Stornováno                   199
PPL         Doručeno                  104156
            Na cestě k příjemci       237593
            Nezadane                    5989
            Převzato dopravcem        169540
            Stornováno                  2951
ČESKÁ POŠTA Doručeno                   30583
            Na cestě k příjemci       114654
            Nezadane                     619
            Převzato dopravcem         27922
            Stornováno                  2113

In [20]:
dupDf.groupby(['provider', 'mapped_status']).agg({'tracking_id':"count"}).unstack()

              tracking_id                                                  \
mapped_status    Doručeno Na cestě k příjemci Nezadane Převzato dopravcem
provider
GEIS                 5101                6186     6151              14947
PPL                104156              237593     5989             169540
ČESKÁ POŠTA         30583              114654      619              27922


mapped_status Stornováno
provider
GEIS                 199
PPL                 2951
ČESKÁ POŠTA         2113

In [21]:
dupDf.groupby(['provider', 'mapped_status']).agg(['min', 'max'])

                                tracking_id                          date  \
                                        min      max                  min
provider    mapped_status
GEIS        Doručeno                1637063  1875579  2018-03-01 08:04:26
            Na cestě k příjemci     1637063  1876214  2018-03-01 05:53:00
            Nezadane                1613267  1876214  2018-03-01 00:01:01
            Převzato dopravcem      1628382  1876214  2018-03-01 00:06:43
            Stornováno              1628382  1865663  2018-03-01 10:08:21
PPL         Doručeno                1415857  1877038  2018-03-01 06:10:04
            Na cestě k příjemci     1589803  1877215  2018-03-01 00:32:50
            Nezadane                1423786  1877153  2018-03-01 06:27:12
            Převzato dopravcem      1589803  1881727  2018-03-01 00:22:06
            Stornováno              1589803  1877015  2018-03-01 05:10:35
ČESKÁ POŠTA Doručeno                1430907  1882069  2018-03-01 06:35:00
            Na cestě k příjemci     1430956  1882076  2018-03-01 00:02:00
            Nezadane                1430956  1876634  2018-03-01 02:42:00
            Převzato dopravcem      1676836  1882077  2018-03-01 06:45:00
            Stornováno              1430956  1873564  2018-03-01 05:51:00

                                                      \
                                                 max
provider    mapped_status
GEIS        Doručeno             2018-04-30 10:57:27
            Na cestě k příjemci  2018-04-30 12:16:00
            Nezadane             2018-04-28 05:12:50
            Převzato dopravcem   2018-04-30 10:58:04
            Stornováno           2018-04-30 03:38:53
PPL         Doručeno             2018-04-30 11:50:19
            Na cestě k příjemci  2018-04-30 11:25:59
            Nezadane             2018-04-30 11:46:24
            Převzato dopravcem   2018-04-30 10:42:52
            Stornováno           2018-04-30 11:09:02
ČESKÁ POŠTA Doručeno             2018-04-30 11:48:00
            Na cestě k příjemci  2018-04-30 13:24:00
            Nezadane             2018-04-30 11:14:00
            Převzato dopravcem   2018-04-30 10:00:00
            Stornováno           2018-04-30 06:49:00

                                                                  status  \
                                                                     min
provider    mapped_status
GEIS        Doručeno                                            Doručení
            Na cestě k příjemci                       Naložení na rozvoz
            Nezadane                                      Naložení na hb
            Převzato dopravcem                      Průchod překladištěm
            Stornováno                                Převzetí odmítnuto
PPL         Doručeno                                            Doručeno
            Na cestě k příjemci   Nedoručeno - adresa neúplná/nenalezena
            Nezadane                       Dobírka - příkaz na zákazníka
            Převzato dopravcem                     Převzetí od zákazníka
            Stornováno                          Nedoručeno - neobjednáno
ČESKÁ POŠTA Doručeno                                            Doručena
            Na cestě k příjemci                     Pořízeno na pochůzku
            Nezadane                Chybně směrována (vinou odesílatele)
            Převzato dopravcem   Řádně podaná zásilka - do rozhodné doby
            Stornováno                         Vrácena - adresát neznámý

                                                                                    \
                                                                               max
provider    mapped_status
GEIS        Doručeno                                                      Doručení
            Na cestě k příjemci                              Řidič nestihl doručit
            Nezadane                                                Naložení na hb
            Převzato dopravcem                                      Příjem na depo
            Stornováno                                            Zpět odesílateli
PPL         Doručeno                                           Doručeno s výhradou
            Na cestě k příjemci                   Zásilku doručujeme na parcelshop
            Nezadane                                                         Výmaz
            Převzato dopravcem                                  Příjem na centrálu
            Stornováno                                            Zpět odesílateli
ČESKÁ POŠTA Doručeno                                                      Doručena
            Na cestě k příjemci                                   Uloženo na poště
            Nezadane             Zásilka byla uložena na pošte (poškozená zásilka)
            Převzato dopravcem             Řádně podaná zásilka - do rozhodné doby
            Stornováno              Zásilka byla dodána zpět (vrácena) odesílateli

                                day     month
                                min max   min max
provider    mapped_status
GEIS        Doručeno              1  30     3   4
            Na cestě k příjemci   1  30     3   4
            Nezadane              1  30     3   4
            Převzato dopravcem    1  30     3   4
            Stornováno            1  30     3   4
PPL         Doručeno              1  31     3   4
            Na cestě k příjemci   1  30     3   4
            Nezadane              1  30     3   4
            Převzato dopravcem    1  31     3   4
            Stornováno            1  30     3   4
ČESKÁ POŠTA Doručeno              1  31     3   4
            Na cestě k příjemci   1  31     3   4
            Nezadane              1  30     3   4
            Převzato dopravcem    1  30     3   4
            Stornováno            1  31     3   4

In [22]:
dupDf.groupby(['provider', 'mapped_status'])["date"].agg(['min', 'max'])

                                                 min                  max
provider    mapped_status
GEIS        Doručeno             2018-03-01 08:04:26  2018-04-30 10:57:27
            Na cestě k příjemci  2018-03-01 05:53:00  2018-04-30 12:16:00
            Nezadane             2018-03-01 00:01:01  2018-04-28 05:12:50
            Převzato dopravcem   2018-03-01 00:06:43  2018-04-30 10:58:04
            Stornováno           2018-03-01 10:08:21  2018-04-30 03:38:53
PPL         Doručeno             2018-03-01 06:10:04  2018-04-30 11:50:19
            Na cestě k příjemci  2018-03-01 00:32:50  2018-04-30 11:25:59
            Nezadane             2018-03-01 06:27:12  2018-04-30 11:46:24
            Převzato dopravcem   2018-03-01 00:22:06  2018-04-30 10:42:52
            Stornováno           2018-03-01 05:10:35  2018-04-30 11:09:02
ČESKÁ POŠTA Doručeno             2018-03-01 06:35:00  2018-04-30 11:48:00
            Na cestě k příjemci  2018-03-01 00:02:00  2018-04-30 13:24:00
            Nezadane             2018-03-01 02:42:00  2018-04-30 11:14:00
            Převzato dopravcem   2018-03-01 06:45:00  2018-04-30 10:00:00
            Stornováno           2018-03-01 05:51:00  2018-04-30 06:49:00

In [23]:
dupDf.groupby(['provider', 'mapped_status']).agg({'tracking_id' : 'median', 'date' : 'count'})

                                 tracking_id    date
provider    mapped_status
GEIS        Doručeno               1776777.0    5101
            Na cestě k příjemci    1782811.5    6186
            Nezadane               1783070.0    6151
            Převzato dopravcem     1785235.0   14947
            Stornováno             1787505.0     199
PPL         Doručeno               1765198.5  104156
            Na cestě k příjemci    1766162.0  237593
            Nezadane               1767701.0    5989
            Převzato dopravcem     1756166.5  169540
            Stornováno             1756128.0    2951
ČESKÁ POŠTA Doručeno               1770375.0   30583
            Na cestě k příjemci    1773549.0  114654
            Nezadane               1752159.0     619
            Převzato dopravcem     1773691.5   27922
            Stornováno             1741430.0    2113

<h2>Práca s duplicitami</h2>

In [24]:
providers_grouped = dupDf[["provider", "tracking_id", "date", "status", "mapped_status"]].sort_values(by=['provider', 'tracking_id', 'date']).groupby(
    ["provider", "tracking_id", "date", "status"])

In [25]:
newDf = providers_grouped.count().sort_values('mapped_status', ascending=False)

In [26]:
newDf.head()

                                                                 mapped_status
provider    tracking_id date                status
GEIS        1750524     2018-03-26 14:33:00 Příjemce nezastižen              3
            1794557     2018-04-17 12:07:43 Příjemce nezastižen              3
ČESKÁ POŠTA 1760088     2018-03-27 05:47:00 Uloženo na poště                 2
            1718791     2018-03-14 05:38:00 Uloženo na poště                 2
            1867230     2018-04-26 06:03:00 Uloženo na poště                 2

In [27]:
dupDf[dupDf["tracking_id"] == 1750524]

,tracking_id,date,status,mapped_status,provider,day,month
423497,1750524,2018-03-23 17:28:19,Příjem na depo,Převzato dopravcem,GEIS,23,3
423498,1750524,2018-03-23 18:25:26,Naložení na hb,Nezadane,GEIS,23,3
423499,1750524,2018-03-23 22:44:10,Průchod překladištěm,Převzato dopravcem,GEIS,23,3
423500,1750524,2018-03-23 22:44:11,Příjem na depo,Převzato dopravcem,GEIS,23,3
423501,1750524,2018-03-26 07:52:00,Naložení na rozvoz,Na cestě k příjemci,GEIS,26,3
423502,1750524,2018-03-26 14:33:00,Příjemce nezastižen,Na cestě k příjemci,GEIS,26,3
423503,1750524,2018-03-26 14:33:00,Příjemce nezastižen,Na cestě k příjemci,GEIS,26,3
423504,1750524,2018-03-26 14:33:00,Příjemce nezastižen,Na cestě k příjemci,GEIS,26,3
423505,1750524,2018-03-26 15:42:48,Příjem na depo,Převzato dopravcem,GEIS,26,3
423506,1750524,2018-03-27 08:26:00,Naložení na rozvoz,Na cestě k příjemci,GEIS,27,3
423507,1750524,2018-03-27 15:26:56,Příjem na depo,Převzato dopravcem,GEIS,27,3
423508,1750524,2018-03-29 13:33:04,Zpět odesílateli,Stornováno,GEIS,29,3

In [28]:
providers_grouped.count().sort_values('mapped_status', ascending=False).values

array([[3],
       [3],
       [2],
       ...,
       [1],
       [1],
       [1]])

In [29]:
duplicateDf = newDf[providers_grouped.count().sort_values('mapped_status', ascending=False).values > 1]

In [31]:
duplicateDf

                                                                      mapped_status
provider    tracking_id date                status
GEIS        1750524     2018-03-26 14:33:00 Příjemce nezastižen                   3
            1794557     2018-04-17 12:07:43 Příjemce nezastižen                   3
ČESKÁ POŠTA 1760088     2018-03-27 05:47:00 Uloženo na poště                      2
            1718791     2018-03-14 05:38:00 Uloženo na poště                      2
            1867230     2018-04-26 06:03:00 Uloženo na poště                      2
            1873468     2018-04-27 05:31:00 Uloženo na poště                      2
            1859283     2018-04-24 07:01:00 Uloženo na poště                      2
                                            Pořízeno na pochůzku                  2
            1806920     2018-04-11 05:51:00 Uloženo na poště                      2
            1780795     2018-04-04 07:18:00 Uloženo na poště                      2
            1675572     2018-03-01 05:37:00 Uloženo na poště                      2
            1769446     2018-03-29 05:39:00 Uloženo na poště                      2
            1801327     2018-04-11 05:11:00 Uloženo na poště                      2
            1762105     2018-03-27 07:15:00 Uloženo na poště                      2
            1804375     2018-04-10 07:24:00 Uloženo na poště                      2
            1752603     2018-03-23 05:43:00 Uloženo na poště                      2
PPL         1757427     2018-03-26 07:36:35 Převážení/vážení                      2
ČESKÁ POŠTA 1788460     2018-04-05 07:21:00 Uloženo na poště                      2
PPL         1755848     2018-03-26 07:36:24 Převážení/vážení                      2
ČESKÁ POŠTA 1806812     2018-04-11 06:01:00 Uloženo na poště                      2
            1827186     2018-04-17 06:14:00 Uloženo na poště                      2
            1690602     2018-03-06 06:24:00 Uloženo na poště                      2
            1780796     2018-04-04 07:18:00 Uloženo na poště                      2
            1787439     2018-04-05 04:15:00 Uloženo na poště                      2
            1795060     2018-04-09 06:47:00 Uloženo na poště                      2
PPL         1699238     2018-03-08 06:42:06 Příjem na rozvozové depo              2
ČESKÁ POŠTA 1703780     2018-03-09 05:13:00 Uloženo na poště                      2
PPL         1749816     2018-03-23 07:12:34 Příjem na rozvozové depo              2
ČESKÁ POŠTA 1876680     2018-04-30 05:45:00 Uloženo na poště                      2
            1714381     2018-03-13 03:16:00 Uloženo na poště                      2
...                                                                             ...
            1700119     2018-03-08 06:06:00 Uloženo na poště                      2
            1737032     2018-03-20 03:05:00 Uloženo na poště                      2
            1877390     2018-04-30 05:29:00 Uloženo na poště                      2
            1842267     2018-04-19 07:45:00 Uloženo na poště                      2
PPL         1756478     2018-03-26 07:36:24 Převážení/vážení                      2
            1794073     2018-04-09 06:45:45 Příjem na rozvozové depo              2
ČESKÁ POŠTA 1773805     2018-04-03 06:44:00 Uloženo na poště                      2
            1714526     2018-03-13 06:30:00 Uloženo na poště                      2
            1719249     2018-03-14 06:21:00 Uloženo na poště                      2
            1826594     2018-04-17 06:39:00 Uloženo na poště                      2
PPL         1685349     2018-03-05 06:10:21 Příjem na rozvozové depo              2
ČESKÁ POŠTA 1826607     2018-04-17 06:01:00 Uloženo na poště                      2
            1704043     2018-03-09 03:21:00 Uloženo na poště                      2
            1675735     2018-03-01 07:38:00 Uloženo na poště                      2
            1815250     2018-04-13 06:57:00 Uloženo na poště                      2
PPL         1757372     2018-03-26 07:36:16 Převážení/vážení                      2
ČESKÁ POŠTA 1727045     2018-03-16 05:02:00 Uloženo na poště                      2
PPL         1804906     2018-04-11 06:53:04 Příjem na rozvozové depo              2
ČESKÁ POŠTA 1810952     2018-04-12 07:12:00 Uloženo na poště                      2
            1694771     2018-03-07 06:21:00 Uloženo na poště                      2
            1747818     2018-03-22 06:25:00 Uloženo na poště                      2
PPL         1727504     2018-03-19 06:52:55 Příjem na rozvozové depo              2
ČESKÁ POŠTA 1767057     2018-03-28 06:22:00 Uloženo na poště                      2
            1877389     2018-04-30 05:09:00 Uloženo na poště                      2
            1834631     2018-04-18 03:12:00 Uloženo na poště                      2
            1808106     2018-04-11 02:51:00 Uloženo na poště                      2
            1859023     2018-04-25 05:15:00 Uloženo na poště                      2
PPL         1687703     2018-03-06 05:52:08 Příjem na rozvozové depo              2
            1805647     2018-04-11 07:10:35 Příjem na rozvozové depo              2
ČESKÁ POŠTA 1801849     2018-04-10 06:49:00 Uloženo na poště                      2

[2594 rows x 1 columns]

In [32]:
duplicateDf.shape

(2594, 1)

In [33]:
dupDf.shape

(728704, 7)

In [34]:
diff = dupDf.shape[0] - duplicateDf.shape[0]
diff

726110

In [35]:
providersNoDup = dupDf.drop_duplicates(['tracking_id', 'date', 'status'], inplace=False)

In [36]:
providersNoDup.shape

(726108, 7)

<h2>Precvičovanie</h2>

Zgrupme si do novej premennej statuses počet statusov za každého providera

In [37]:
statuses = providersNoDup.groupby(["status", "provider"]).count()

In [38]:
statuses.head()

,,tracking_id,date,mapped_status,day,month
status,provider,,,,,
Chybně směrována (vinou odesílatele),ČESKÁ POŠTA,1,1,1,1,1
Chybně směrována vinou pošty (zpět na spu),ČESKÁ POŠTA,338,338,338,338,338
Dobírka - příkaz na zákazníka,PPL,180,180,180,180,180
Dobírka - zaplaceno zákazníkovi,PPL,155,155,155,155,155
Doručena,ČESKÁ POŠTA,30583,30583,30583,30583,30583

In [39]:
statuses.shape

(65, 5)

Zoraďme si statusy podľa počtu od najvyššieho

In [40]:
statuses = statuses.sort_values("tracking_id", ascending = 0)
statuses.head()

,,tracking_id,date,mapped_status,day,month
status,provider,,,,,
Příjem na rozvozové depo,PPL,120610,120610,120610,120610,120610
Zásilku doručujeme na parcelshop,PPL,108803,108803,108803,108803,108803
Převážení/vážení,PPL,107630,107630,107630,107630,107630
Doručeno,PPL,104130,104130,104130,104130,104130
Příjem na centrálu,PPL,61563,61563,61563,61563,61563

Vypíšme si najčastejšie sa vyskytujúci status naprieč všetkými providermi

In [41]:
statuses.tracking_id.idxmax()

('Příjem na rozvozové depo', 'PPL')

Vypíšme si najmenej často sa vyskytujúci status naprieč všetkými providermi

In [42]:
statuses.tracking_id.idxmin()

('Nasnímáno na kurz', 'ČESKÁ POŠTA')

Koľko odlišných názvov statusov má najmenej výskytov

In [43]:
statuses[statuses.tracking_id == statuses.tracking_id.min()]

,,tracking_id,date,mapped_status,day,month
status,provider,,,,,
Nasnímáno na kurz,ČESKÁ POŠTA,1,1,1,1,1
Vráceno - nedostatečná adresa,ČESKÁ POŠTA,1,1,1,1,1
Chybně směrována (vinou odesílatele),ČESKÁ POŠTA,1,1,1,1,1

In [44]:
len(statuses[statuses.tracking_id == statuses.tracking_id.min()])

3

<h2>Iterácia</h2>

In [49]:
count = 0

In [50]:
for index, group in providers_grouped:
    if count == 1:
        break
    else:
        print (group)
        print (group.provider)
        print (group.provider.values)
        print (group.provider.values[0])
        print([group.mapped_status.values[0], str(group.provider.values[0]) + "-" + str(group.tracking_id.values[0])])
    count = count+1

       provider  tracking_id                 date          status  \
728536     GEIS      1613267  2018-03-19 20:03:30  Naložení na hb

       mapped_status
728536      Nezadane
728536    GEIS
Name: provider, dtype: object
['GEIS']
GEIS
['Nezadane', 'GEIS-1613267']

<h2>Funkcie v Pythone</h2>

<p>Ak chceme v programovaní niečo zautomatizovať, alebo nechceme dookola písať rovnaké bloky kódu, môžeme si napísať vlastné funkcie. S funkciami sme sa už stretli. Boli to rôzne vstavané funkcie Pythonu, či už funkcie (metódy) dátových typov, modulu math alebo základné funkcie ako <code>print()</code>, <code>range()</code> atď. Pre vysvetlenie, ako funkcie fungujú, si ukážeme ako ich vytvárať.

Na vytvorenie funkcie v Pythone sa používa slovíčko <code>def</code>, za ktorým nasleduje názov funkcie, okrúhle zátvorky obsahujúce názvy parametrov pre funkciu a dvojbodka, tak ako tomu je aj pri cykloch či podmienkach.

<img src="https://mpicbg-scicomp.github.io/dlbc17-python-intro/fig/python-function.svg" />

In [53]:
def say_hello():
    print ('Hello')

Aby sme videli výsledok funkcie, je potrebné ju zavolať. Volanie sa uskutočňuje pomocou názvu funkcie.

In [54]:
say_hello()

Hello

<h2>Parametre funkcie</h2>

In [55]:
def say_hello(name):
    print ('Hello', name)

In [56]:
say_hello('Sveta')

Hello Sveta

<h2>Návratová hodnota funkcie - return</h2>

In [57]:
def say_hello(name):
    return name

def print_hello():
    print ('Hello', say_hello('Sveta'))

In [58]:
print_hello()

Hello Sveta

<h2>Voliteľný parameter</h2>

In [59]:
def say_hello(name='Sveta'):
    print ('Hello', name)

In [60]:
say_hello()

Hello Sveta

In [61]:
say_hello('Harry')

Hello Harry

<h2>Viacero parametrov</h2>

In [62]:
def say_greeting(name, greeting):
    print (greeting, name)

In [63]:
say_greeting('Sveta', 'Hi')

Hi Sveta

<h2>Funkcia s ľubovoľným počtom parametrov</h2>

In [64]:
def say_hello(*names):
    for i in names:
        print ('Hello', i)

In [65]:
say_hello('Sveta', 'Harry', 'Ron')

Hello Sveta
Hello Harry
Hello Ron

<h2>Viacero návratových hodnôt</h2>

In [66]:
def say_hello():
    return ('Hi', 'Hello')

In [67]:
a, b = say_hello()

In [68]:
print (a, b)

Hi Hello

<h2>Rozdiel medzi parametrom a argumentom</h2>

In [69]:
def say_hello(name):
    print (name)

name je parametrom funkcie

In [70]:
say_hello('Sveta')

Sveta

'Sveta' je argumentom funkcie pri jej volaní

<h2>Funkcia vs. metóda</h2>

<p>Ste zvedaví, prečo voláme niekedy funkciu s bodkou (.) na konci reťazca (ako <code>"Sveta".upper()</code>) a niekedy najprv voláme funkciu a reťazec vložíme do zátvoriek (<code>len("Sveta")</code>)? V niektorých prípadoch funkcie patria k objektom, ako napr. <code>upper()</code>, čo môže byt vykonaná len na reťazcoch. V takomto prípade sa tieto funkcie volajú <b>metódy</b>. Inokedy funkcie nepatria k žiadnemu konkrétnemu objektu a môžu byť použité na rôzne typy objektov, rovnako ako <code>len()</code>. Preto zadáme "Sveta" ako parameter pre funkciu len.</p>

In [71]:
"Sveta".upper()

'SVETA'

In [72]:
[1, 2, 3].upper()

AttributeError: 'list' object has no attribute 'upper'

In [73]:
len("Sveta")

5

In [74]:
len([1, 2, 3])

3

<h2>Úlohy</h2>

<ul>
    <li>Napíš funkciu s názvom <b>find_numbers</b> , ktorá akceptuje vstupný parameter zoznam obsahujúci ľubovoľný počet hodnôt. Následne prejdi všetkými hodnotami v zozname a: <br />
ak je hodnota kladné sudé celé číslo vypíš  “Sudé číslo: {číslo}" <br />
ak je hodnota kladné liché celé číslo vypíš “Liché číslo: {číslo}" <br />
ak je hodnota záporné číslo  vypíš “Chyba, záporné číslo: {číslo}” <br />
Vysvetlivky: hodnota v {} je nahradená konkrétnym číslom/hodnotou zo zoznamu<br />
        Funkciu aplikuj nad zoznamom [1, -23, 12, 24, 13]</li>
    <li>Napíš funkciu s názvom <b>math_dict</b>, ktorá pre argumentom zadané číslo <b>n</b> vytvorí a vráti slovník (dictionary) , kde ako kľúče sú čísla od 1 po n, a ako hodnoty sú ich druhé mocniny</li>
</ul>

In [75]:
def find_numbers(my_list):
    for i in my_list:
        if i % 2 == 0 and i > 0:
            print ('Sudé číslo:', i)
        elif i % 2 != 0 and i > 0:
            print ('Liché číslo:', i)
        else:
            print ('Chyba, záporné číslo:', i)

In [76]:
find_numbers([1, -23, 12, 24, 13])

Liché číslo: 1
Chyba, záporné číslo: -23
Sudé číslo: 12
Sudé číslo: 24
Liché číslo: 13

In [77]:
def math_dict(n):
    new_dict = {}
    for i in range(1,n+1):
       new_dict[i] = i**2
    return new_dict

In [78]:
print(math_dict(23))

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225, 16: 256, 17: 289, 18: 324, 19: 361, 20: 400, 21: 441, 22: 484, 23: 529}

<h2>Použitie funkcií v Pandase</h2>

<p>V Pandase si môžeme rovnako ako v Pythone definovať vlastné funkcie. Pre aplikovanie vybranej funkcie nad dátovým setom (riadkom/stĺpcom) používame <code>apply()</code></p>

In [84]:
from datetime import timedelta

In [85]:
providersNoDup["date"] = pd.to_datetime(providersNoDup.loc[:, "date"])

/Users/svetlanamargetova/Desktop/digital_academy3/venv/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [86]:
def delivery_d1(date):
    return date + timedelta(days=1)

In [87]:
providersNoDup["delivery_d1"] = providersNoDup["date"].apply(delivery_d1)

/Users/svetlanamargetova/Desktop/digital_academy3/venv/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [88]:
providersNoDup.head()

,tracking_id,date,status,mapped_status,provider,day,month,delivery_d1
0,1882077,2018-04-30 07:14:00,Řádně podaná zásilka - do rozhodné doby,Převzato dopravcem,ČESKÁ POŠTA,30,4,2018-05-01 07:14:00
1,1882076,2018-04-30 06:52:00,Pořízeno na pochůzku,Na cestě k příjemci,ČESKÁ POŠTA,30,4,2018-05-01 06:52:00
2,1882075,2018-04-30 06:52:00,Uloženo na poště,Na cestě k příjemci,ČESKÁ POŠTA,30,4,2018-05-01 06:52:00
3,1882075,2018-04-30 06:58:00,Uloženo na poště,Na cestě k příjemci,ČESKÁ POŠTA,30,4,2018-05-01 06:58:00
4,1882075,2018-04-30 07:14:00,Řádně podaná zásilka - do rozhodné doby,Převzato dopravcem,ČESKÁ POŠTA,30,4,2018-05-01 07:14:00

<h2>Úlohy</h2>
<ul>
    <li>Napíšte funkciu s názvom <b>status_len</b>, ktorá zistí dĺžku statusu v každom riadku a priradí do nového stĺpca s názvom <b>status_length</b></li>
</ul>

In [89]:
def status_len(status):
    return len(status)

In [90]:
providersNoDup["status_length"] = providersNoDup.loc[:, "status"].apply(status_len)

/Users/svetlanamargetova/Desktop/digital_academy3/venv/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [91]:
providersNoDup.head()

,tracking_id,date,status,mapped_status,provider,day,month,delivery_d1,status_length
0,1882077,2018-04-30 07:14:00,Řádně podaná zásilka - do rozhodné doby,Převzato dopravcem,ČESKÁ POŠTA,30,4,2018-05-01 07:14:00,39
1,1882076,2018-04-30 06:52:00,Pořízeno na pochůzku,Na cestě k příjemci,ČESKÁ POŠTA,30,4,2018-05-01 06:52:00,20
2,1882075,2018-04-30 06:52:00,Uloženo na poště,Na cestě k příjemci,ČESKÁ POŠTA,30,4,2018-05-01 06:52:00,16
3,1882075,2018-04-30 06:58:00,Uloženo na poště,Na cestě k příjemci,ČESKÁ POŠTA,30,4,2018-05-01 06:58:00,16
4,1882075,2018-04-30 07:14:00,Řádně podaná zásilka - do rozhodné doby,Převzato dopravcem,ČESKÁ POŠTA,30,4,2018-05-01 07:14:00,39

In [93]:
providersNoDup.to_csv('../csv/providers_update.csv', encoding='utf-8', index = False)