In [1]:
import pandas as pd
import numpy as np

In [2]:
"""
Načítajte si do novej premennej cez read_json dáta
o kurzoch Czechitas z adresy https://czechitas-app.herokuapp.com/api/v1/courses/open/
"""
coursesDf = pd.read_json('https://czechitas-app.herokuapp.com/api/v1/courses/open/')

In [3]:
"""
Vypíšte si prvých 5 riadkov cez head()
"""
coursesDf.head()

,contact_person,couches,course_category,course_description,course_end_date,course_price,course_start_date,course_venue,id,interested_form_link,max_capacity,notes,open_registration,publish,registration_form_link,repeat,title
0,"{'id': 4, 'user': 'info@czechitas.cz'}",Anna Pascenko,"{'id': 2, 'title': 'I can code!', 'color_code'...",Have you already implemented any application o...,2016-11-26T16:30:00Z,300,2016-11-26T08:30:00Z,"{'id': 11, 'title': 'Konica Minolta', 'street_...",67,https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,NaN,,True,True,https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,,I can code!: Introduction to databases
1,"{'id': 4, 'user': 'info@czechitas.cz'}",Pavel Lasák,"{'id': 11, 'title': 'Exceluju!', 'color_code':...","Máme tady další Excel workshop, protože vás po...",2016-12-03T16:30:00Z,300,2016-12-03T08:00:00Z,"{'id': 3, 'title': 'Fakulta informatiky Masary...",66,https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,NaN,Osnova workshopu:\r\n– Základy + pár efektivní...,True,True,https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,,Excel workshop
2,"{'id': 4, 'user': 'info@czechitas.cz'}",,"{'id': 2, 'title': 'I can code!', 'color_code'...","Láká tě programování, ale vůbec nevíš, jak bys...",2016-12-03T17:00:00Z,300,2016-12-03T09:00:00Z,"{'id': 1, 'title': 'Impact Hub', 'street_name'...",65,https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,NaN,"Vlastní notebook, myš (není nutná, ale bude se...",True,True,https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,,Úvod do programování
3,"{'id': 4, 'user': 'info@czechitas.cz'}",Martina Votrubová,"{'id': 13, 'title': 'Jsem digitální', 'color_c...","Sociální sítě dnes používá snad každý, ale víš...",2016-11-23T19:00:00Z,300,2016-11-23T16:00:00Z,"{'id': 5, 'title': 'CERGE-EI', 'street_name': ...",58,https://goo.gl/forms/DhfY21CiwIasezAY2,NaN,Blok a tužku a dobrou náladu!,True,True,https://goo.gl/forms/DhfY21CiwIasezAY2,,Jsem digitální!: Sociální sítě
4,"{'id': 4, 'user': 'info@czechitas.cz'}",Pavel Ungr,"{'id': 13, 'title': 'Jsem digitální', 'color_c...","Nejen programování je člověk živ, a proto ti p...",2016-11-28T20:00:00Z,300,2016-11-28T17:00:00Z,"{'id': 7, 'title': 'Impact Hub', 'street_name'...",59,https://goo.gl/forms/DhfY21CiwIasezAY2,NaN,"Vlastní notebook, myš (není nutná, ale bude se...",True,True,https://goo.gl/forms/DhfY21CiwIasezAY2,,Jsem digitální!: SEO interaktivní workshop

In [4]:
"""
Vypíšte si základné informácie o dátovom sete, dátové typy, null hodnoty, názvy stĺpcov cez príslušnú metódu
"""
coursesDf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13 entries, 0 to 12
Data columns (total 17 columns):
contact_person            13 non-null object
couches                   13 non-null object
course_category           13 non-null object
course_description        13 non-null object
course_end_date           13 non-null object
course_price              13 non-null int64
course_start_date         13 non-null object
course_venue              13 non-null object
id                        13 non-null int64
interested_form_link      13 non-null object
max_capacity              0 non-null float64
notes                     13 non-null object
open_registration         13 non-null bool
publish                   13 non-null bool
registration_form_link    13 non-null object
repeat                    13 non-null object
title                     13 non-null object
dtypes: bool(2), float64(1), int64(2), object(12)
memory usage: 1.7+ KB

In [5]:
"""
Vypíšte si počet riadkov a stĺpcov daného dátového setu
"""
coursesDf.shape

(13, 17)

In [6]:
"""
Vypíšte si posledných 6 hodnôt
"""
coursesDf.tail(6)

,contact_person,couches,course_category,course_description,course_end_date,course_price,course_start_date,course_venue,id,interested_form_link,max_capacity,notes,open_registration,publish,registration_form_link,repeat,title
7,"{'id': 4, 'user': 'info@czechitas.cz'}",,"{'id': 2, 'title': 'I can code!', 'color_code'...","Zajímá tě, co to funkcionální programování je ...",2016-11-12T17:00:00Z,300,2016-11-12T08:00:00Z,"{'id': 7, 'title': 'Impact Hub', 'street_name'...",62,https://goo.gl/forms/DhfY21CiwIasezAY2,NaN,"Vlastní notebook, myš (není nutná, ale bude se...",True,True,https://goo.gl/forms/DhfY21CiwIasezAY2,,Programuju!: Funkcionální programování Praha
8,"{'id': 4, 'user': 'info@czechitas.cz'}",Kuan-Heng Lin,"{'id': 2, 'title': 'I can code!', 'color_code'...",Czechitas will have course in English! Again! ...,2016-11-15T18:30:00Z,500,2016-10-25T16:00:00Z,"{'id': 5, 'title': 'CERGE-EI', 'street_name': ...",50,https://goo.gl/forms/DhfY21CiwIasezAY2,NaN,Prerequisities: The Course is for absolute beg...,True,True,https://goo.gl/forms/DhfY21CiwIasezAY2,every Tuesday,I can code!: Basics of R programming
9,"{'id': 4, 'user': 'info@czechitas.cz'}",Pavel Lasák,"{'id': 11, 'title': 'Exceluju!', 'color_code':...",Chceš konečně pochopit Excel?!\r\n \r\nExcel j...,2016-10-22T15:30:00Z,300,2016-10-22T07:00:00Z,"{'id': 4, 'title': 'Kampus', 'street_name': 'P...",49,https://goo.gl/forms/DhfY21CiwIasezAY2,NaN,Osnova workshopu:\r\n– Základy + pár efektivní...,True,True,https://goo.gl/forms/DhfY21CiwIasezAY2,,Excel workshop
10,"{'id': 4, 'user': 'info@czechitas.cz'}",,"{'id': 2, 'title': 'I can code!', 'color_code'...","Láká tě programování, ale vůbec nevíš, jak bys...",2016-10-16T15:30:00Z,300,2016-10-16T07:00:00Z,"{'id': 1, 'title': 'Impact Hub', 'street_name'...",53,https://goo.gl/forms/DhfY21CiwIasezAY2,NaN,"Co s sebou: Vlastní notebook, myš (není nutná,...",True,True,https://goo.gl/forms/DhfY21CiwIasezAY2,,Úvod do programování
11,"{'id': 4, 'user': 'info@czechitas.cz'}",,"{'id': 1, 'title': 'Web development!', 'color_...",​Cílem kurzu je získání praktických zkušeností...,2016-12-14T19:00:00Z,2000,2016-09-21T16:00:00Z,"{'id': 3, 'title': 'Fakulta informatiky Masary...",55,https://goo.gl/forms/DhfY21CiwIasezAY2,NaN,PRO KOHO JE KURZ URČEN: Kurz je určen pro dívk...,True,True,https://goo.gl/forms/DhfY21CiwIasezAY2,,Tvořím web: od A do Z!
12,"{'id': 4, 'user': 'info@czechitas.cz'}",Vladimír Valouch,"{'id': 2, 'title': 'I can code!', 'color_code'...",Did you know that mobile app development is on...,2016-12-13T20:00:00Z,2000,2016-10-11T16:00:00Z,"{'id': 7, 'title': 'Impact Hub', 'street_name'...",54,https://goo.gl/forms/DhfY21CiwIasezAY2,NaN,Prerequisities: Basic knowledge of programming...,True,True,https://goo.gl/forms/DhfY21CiwIasezAY2,,I can code!: Android course

In [7]:
"""
Vypíšte všetky riadky zo stĺpca couches
"""
coursesDf["couches"]

0         Anna Pascenko
1           Pavel Lasák
2
3     Martina Votrubová
4            Pavel Ungr
5
6
7
8         Kuan-Heng Lin
9           Pavel Lasák
10
11
12     Vladimír Valouch
Name: couches, dtype: object

In [8]:
"""
Vypíšte si dáta medzi 5 a 10 riadkov a zo stĺpcov medzi course_category až po stĺpec course_price
"""
coursesDf.iloc[6:10, 2:6]

,course_category,course_description,course_end_date,course_price
6,"{'id': 1, 'title': 'Web development!', 'color_...","Umíš dělat HTML stránky, ale chceš zjistit, ja...",2016-11-12T17:00:00Z,300
7,"{'id': 2, 'title': 'I can code!', 'color_code'...","Zajímá tě, co to funkcionální programování je ...",2016-11-12T17:00:00Z,300
8,"{'id': 2, 'title': 'I can code!', 'color_code'...",Czechitas will have course in English! Again! ...,2016-11-15T18:30:00Z,500
9,"{'id': 11, 'title': 'Exceluju!', 'color_code':...",Chceš konečně pochopit Excel?!\r\n \r\nExcel j...,2016-10-22T15:30:00Z,300

In [9]:
"""
Zmente defaultný pandas index na index stĺpca id
"""
coursesDf = coursesDf.set_index("id")

In [10]:
"""
Vypíšte si dáta z labelmi od 50 po 55 nad stĺpcami couches, course_price, notes
"""
coursesDf.loc[50:55, ["couches", "course_price", "notes"]]

,couches,course_price,notes
id,,,
50,Kuan-Heng Lin,500,Prerequisities: The Course is for absolute beg...
49,Pavel Lasák,300,Osnova workshopu:\r\n– Základy + pár efektivní...
53,,300,"Co s sebou: Vlastní notebook, myš (není nutná,..."
55,,2000,PRO KOHO JE KURZ URČEN: Kurz je určen pro dívk...

In [11]:
"""
Upravte všetky mená koučov s stĺpci couches na veľké písmená a uložte do daného stĺpca
"""
coursesDf["couches"] = coursesDf["couches"].str.upper()
coursesDf.head()

,contact_person,couches,course_category,course_description,course_end_date,course_price,course_start_date,course_venue,interested_form_link,max_capacity,notes,open_registration,publish,registration_form_link,repeat,title
id,,,,,,,,,,,,,,,,
67,"{'id': 4, 'user': 'info@czechitas.cz'}",ANNA PASCENKO,"{'id': 2, 'title': 'I can code!', 'color_code'...",Have you already implemented any application o...,2016-11-26T16:30:00Z,300,2016-11-26T08:30:00Z,"{'id': 11, 'title': 'Konica Minolta', 'street_...",https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,NaN,,True,True,https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,,I can code!: Introduction to databases
66,"{'id': 4, 'user': 'info@czechitas.cz'}",PAVEL LASÁK,"{'id': 11, 'title': 'Exceluju!', 'color_code':...","Máme tady další Excel workshop, protože vás po...",2016-12-03T16:30:00Z,300,2016-12-03T08:00:00Z,"{'id': 3, 'title': 'Fakulta informatiky Masary...",https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,NaN,Osnova workshopu:\r\n– Základy + pár efektivní...,True,True,https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,,Excel workshop
65,"{'id': 4, 'user': 'info@czechitas.cz'}",,"{'id': 2, 'title': 'I can code!', 'color_code'...","Láká tě programování, ale vůbec nevíš, jak bys...",2016-12-03T17:00:00Z,300,2016-12-03T09:00:00Z,"{'id': 1, 'title': 'Impact Hub', 'street_name'...",https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,NaN,"Vlastní notebook, myš (není nutná, ale bude se...",True,True,https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,,Úvod do programování
58,"{'id': 4, 'user': 'info@czechitas.cz'}",MARTINA VOTRUBOVÁ,"{'id': 13, 'title': 'Jsem digitální', 'color_c...","Sociální sítě dnes používá snad každý, ale víš...",2016-11-23T19:00:00Z,300,2016-11-23T16:00:00Z,"{'id': 5, 'title': 'CERGE-EI', 'street_name': ...",https://goo.gl/forms/DhfY21CiwIasezAY2,NaN,Blok a tužku a dobrou náladu!,True,True,https://goo.gl/forms/DhfY21CiwIasezAY2,,Jsem digitální!: Sociální sítě
59,"{'id': 4, 'user': 'info@czechitas.cz'}",PAVEL UNGR,"{'id': 13, 'title': 'Jsem digitální', 'color_c...","Nejen programování je člověk živ, a proto ti p...",2016-11-28T20:00:00Z,300,2016-11-28T17:00:00Z,"{'id': 7, 'title': 'Impact Hub', 'street_name'...",https://goo.gl/forms/DhfY21CiwIasezAY2,NaN,"Vlastní notebook, myš (není nutná, ale bude se...",True,True,https://goo.gl/forms/DhfY21CiwIasezAY2,,Jsem digitální!: SEO interaktivní workshop

In [12]:
"""
Vypíšte počet prázdnych hodnôt zo stĺpca max_capacity
"""
coursesDf["max_capacity"].isnull().sum()

13

In [13]:
"""
Nahraďte v stĺpci max_capacity prázdne hodnoty, hodnotou 0 a nastavte ako int dátový typ
"""
coursesDf["max_capacity"] = coursesDf["max_capacity"].fillna(1).astype(np.int)
coursesDf.head()

,contact_person,couches,course_category,course_description,course_end_date,course_price,course_start_date,course_venue,interested_form_link,max_capacity,notes,open_registration,publish,registration_form_link,repeat,title
id,,,,,,,,,,,,,,,,
67,"{'id': 4, 'user': 'info@czechitas.cz'}",ANNA PASCENKO,"{'id': 2, 'title': 'I can code!', 'color_code'...",Have you already implemented any application o...,2016-11-26T16:30:00Z,300,2016-11-26T08:30:00Z,"{'id': 11, 'title': 'Konica Minolta', 'street_...",https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,1,,True,True,https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,,I can code!: Introduction to databases
66,"{'id': 4, 'user': 'info@czechitas.cz'}",PAVEL LASÁK,"{'id': 11, 'title': 'Exceluju!', 'color_code':...","Máme tady další Excel workshop, protože vás po...",2016-12-03T16:30:00Z,300,2016-12-03T08:00:00Z,"{'id': 3, 'title': 'Fakulta informatiky Masary...",https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,1,Osnova workshopu:\r\n– Základy + pár efektivní...,True,True,https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,,Excel workshop
65,"{'id': 4, 'user': 'info@czechitas.cz'}",,"{'id': 2, 'title': 'I can code!', 'color_code'...","Láká tě programování, ale vůbec nevíš, jak bys...",2016-12-03T17:00:00Z,300,2016-12-03T09:00:00Z,"{'id': 1, 'title': 'Impact Hub', 'street_name'...",https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,1,"Vlastní notebook, myš (není nutná, ale bude se...",True,True,https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,,Úvod do programování
58,"{'id': 4, 'user': 'info@czechitas.cz'}",MARTINA VOTRUBOVÁ,"{'id': 13, 'title': 'Jsem digitální', 'color_c...","Sociální sítě dnes používá snad každý, ale víš...",2016-11-23T19:00:00Z,300,2016-11-23T16:00:00Z,"{'id': 5, 'title': 'CERGE-EI', 'street_name': ...",https://goo.gl/forms/DhfY21CiwIasezAY2,1,Blok a tužku a dobrou náladu!,True,True,https://goo.gl/forms/DhfY21CiwIasezAY2,,Jsem digitální!: Sociální sítě
59,"{'id': 4, 'user': 'info@czechitas.cz'}",PAVEL UNGR,"{'id': 13, 'title': 'Jsem digitální', 'color_c...","Nejen programování je člověk živ, a proto ti p...",2016-11-28T20:00:00Z,300,2016-11-28T17:00:00Z,"{'id': 7, 'title': 'Impact Hub', 'street_name'...",https://goo.gl/forms/DhfY21CiwIasezAY2,1,"Vlastní notebook, myš (není nutná, ale bude se...",True,True,https://goo.gl/forms/DhfY21CiwIasezAY2,,Jsem digitální!: SEO interaktivní workshop

In [14]:
"""
Vypíšte kurzy, kde lektorom je Pavel Lasák
"""
coursesDf[coursesDf["couches"] == 'PAVEL LASÁK']

,contact_person,couches,course_category,course_description,course_end_date,course_price,course_start_date,course_venue,interested_form_link,max_capacity,notes,open_registration,publish,registration_form_link,repeat,title
id,,,,,,,,,,,,,,,,
66,"{'id': 4, 'user': 'info@czechitas.cz'}",PAVEL LASÁK,"{'id': 11, 'title': 'Exceluju!', 'color_code':...","Máme tady další Excel workshop, protože vás po...",2016-12-03T16:30:00Z,300,2016-12-03T08:00:00Z,"{'id': 3, 'title': 'Fakulta informatiky Masary...",https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,1,Osnova workshopu:\r\n– Základy + pár efektivní...,True,True,https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,,Excel workshop
49,"{'id': 4, 'user': 'info@czechitas.cz'}",PAVEL LASÁK,"{'id': 11, 'title': 'Exceluju!', 'color_code':...",Chceš konečně pochopit Excel?!\r\n \r\nExcel j...,2016-10-22T15:30:00Z,300,2016-10-22T07:00:00Z,"{'id': 4, 'title': 'Kampus', 'street_name': 'P...",https://goo.gl/forms/DhfY21CiwIasezAY2,1,Osnova workshopu:\r\n– Základy + pár efektivní...,True,True,https://goo.gl/forms/DhfY21CiwIasezAY2,,Excel workshop

In [15]:
"""
Vypíšte kurzy, ktoré začínajú  v rozmedzí dátumov od 01. 12. 2016 do 31. 12. 2016
"""
coursesDf[["title", "course_start_date"]][(pd.to_datetime(coursesDf["course_start_date"]).dt.month.between(12,12))]

                   title     course_start_date
id
66        Excel workshop  2016-12-03T08:00:00Z
65  Úvod do programování  2016-12-03T09:00:00Z

In [16]:
coursesDf[["title", "course_start_date"]][(pd.to_datetime(coursesDf["course_start_date"]).dt.month == 12)]

                   title     course_start_date
id
66        Excel workshop  2016-12-03T08:00:00Z
65  Úvod do programování  2016-12-03T09:00:00Z

In [17]:
"""
Vypíšte kurzy, ktoré sú drahšie ako 1500 Kč a nemajú žiadneho lektora
"""
coursesDf[(coursesDf["course_price"] > 1500) & (coursesDf["couches"] == '')]

,contact_person,couches,course_category,course_description,course_end_date,course_price,course_start_date,course_venue,interested_form_link,max_capacity,notes,open_registration,publish,registration_form_link,repeat,title
id,,,,,,,,,,,,,,,,
55,"{'id': 4, 'user': 'info@czechitas.cz'}",,"{'id': 1, 'title': 'Web development!', 'color_...",​Cílem kurzu je získání praktických zkušeností...,2016-12-14T19:00:00Z,2000,2016-09-21T16:00:00Z,"{'id': 3, 'title': 'Fakulta informatiky Masary...",https://goo.gl/forms/DhfY21CiwIasezAY2,1,PRO KOHO JE KURZ URČEN: Kurz je určen pro dívk...,True,True,https://goo.gl/forms/DhfY21CiwIasezAY2,,Tvořím web: od A do Z!

In [18]:
"""
Vypíšte kurzy, kde cena je 300 Kč alebo kurzy, kde koučom je Pavel Ungr
"""
coursesDf[(coursesDf["course_price"] == 300) | (coursesDf["couches"] == 'PAVEL UNGR')]

,contact_person,couches,course_category,course_description,course_end_date,course_price,course_start_date,course_venue,interested_form_link,max_capacity,notes,open_registration,publish,registration_form_link,repeat,title
id,,,,,,,,,,,,,,,,
67,"{'id': 4, 'user': 'info@czechitas.cz'}",ANNA PASCENKO,"{'id': 2, 'title': 'I can code!', 'color_code'...",Have you already implemented any application o...,2016-11-26T16:30:00Z,300,2016-11-26T08:30:00Z,"{'id': 11, 'title': 'Konica Minolta', 'street_...",https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,1,,True,True,https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,,I can code!: Introduction to databases
66,"{'id': 4, 'user': 'info@czechitas.cz'}",PAVEL LASÁK,"{'id': 11, 'title': 'Exceluju!', 'color_code':...","Máme tady další Excel workshop, protože vás po...",2016-12-03T16:30:00Z,300,2016-12-03T08:00:00Z,"{'id': 3, 'title': 'Fakulta informatiky Masary...",https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,1,Osnova workshopu:\r\n– Základy + pár efektivní...,True,True,https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,,Excel workshop
65,"{'id': 4, 'user': 'info@czechitas.cz'}",,"{'id': 2, 'title': 'I can code!', 'color_code'...","Láká tě programování, ale vůbec nevíš, jak bys...",2016-12-03T17:00:00Z,300,2016-12-03T09:00:00Z,"{'id': 1, 'title': 'Impact Hub', 'street_name'...",https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,1,"Vlastní notebook, myš (není nutná, ale bude se...",True,True,https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,,Úvod do programování
58,"{'id': 4, 'user': 'info@czechitas.cz'}",MARTINA VOTRUBOVÁ,"{'id': 13, 'title': 'Jsem digitální', 'color_c...","Sociální sítě dnes používá snad každý, ale víš...",2016-11-23T19:00:00Z,300,2016-11-23T16:00:00Z,"{'id': 5, 'title': 'CERGE-EI', 'street_name': ...",https://goo.gl/forms/DhfY21CiwIasezAY2,1,Blok a tužku a dobrou náladu!,True,True,https://goo.gl/forms/DhfY21CiwIasezAY2,,Jsem digitální!: Sociální sítě
59,"{'id': 4, 'user': 'info@czechitas.cz'}",PAVEL UNGR,"{'id': 13, 'title': 'Jsem digitální', 'color_c...","Nejen programování je člověk živ, a proto ti p...",2016-11-28T20:00:00Z,300,2016-11-28T17:00:00Z,"{'id': 7, 'title': 'Impact Hub', 'street_name'...",https://goo.gl/forms/DhfY21CiwIasezAY2,1,"Vlastní notebook, myš (není nutná, ale bude se...",True,True,https://goo.gl/forms/DhfY21CiwIasezAY2,,Jsem digitální!: SEO interaktivní workshop
61,"{'id': 4, 'user': 'info@czechitas.cz'}",,"{'id': 2, 'title': 'I can code!', 'color_code'...","Láká tě programování, ale vůbec nevíš, jak bys...",2016-11-19T16:30:00Z,300,2016-11-19T08:30:00Z,"{'id': 7, 'title': 'Impact Hub', 'street_name'...",https://goo.gl/forms/DhfY21CiwIasezAY2,1,"Vlastní notebook s Windows, myš (není nutná, a...",True,True,https://goo.gl/forms/DhfY21CiwIasezAY2,,Programuju!: Úvod do programování v C# Praha
63,"{'id': 4, 'user': 'info@czechitas.cz'}",,"{'id': 1, 'title': 'Web development!', 'color_...","Umíš dělat HTML stránky, ale chceš zjistit, ja...",2016-11-12T17:00:00Z,300,2016-11-12T09:00:00Z,"{'id': 1, 'title': 'Impact Hub', 'street_name'...",https://goo.gl/forms/DhfY21CiwIasezAY2,1,"Vlastní notebook, myš (není nutná, ale bude se...",True,True,https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,,Tvořím web!: Jak si ochočit PHP
62,"{'id': 4, 'user': 'info@czechitas.cz'}",,"{'id': 2, 'title': 'I can code!', 'color_code'...","Zajímá tě, co to funkcionální programování je ...",2016-11-12T17:00:00Z,300,2016-11-12T08:00:00Z,"{'id': 7, 'title': 'Impact Hub', 'street_name'...",https://goo.gl/forms/DhfY21CiwIasezAY2,1,"Vlastní notebook, myš (není nutná, ale bude se...",True,True,https://goo.gl/forms/DhfY21CiwIasezAY2,,Programuju!: Funkcionální programování Praha
49,"{'id': 4, 'user': 'info@czechitas.cz'}",PAVEL LASÁK,"{'id': 11, 'title': 'Exceluju!', 'color_code':...",Chceš konečně pochopit Excel?!\r\n \r\nExcel j...,2016-10-22T15:30:00Z,300,2016-10-22T07:00:00Z,"{'id': 4, 'title': 'Kampus', 'street_name': 'P...",https://goo.gl/forms/DhfY21CiwIasezAY2,1,Osnova workshopu:\r\n– Základy + pár efektivní...,True,True,https://goo.gl/forms/DhfY21CiwIasezAY2,,Excel workshop
53,"{'id': 4, 'user': 'info@czechitas.cz'}",,"{'id': 2, 'title': 'I can code!', 'color_code'...","Láká tě programování, ale vůbec nevíš, jak bys...",2016-10-16T15:30:00Z,300,2016-10-16T07:00:00Z,"{'id': 1, 'title': 'Impact Hub', 'street_name'...",https://goo.gl/forms/DhfY21CiwIasezAY2,1,"Co s sebou: Vlastní notebook, myš (není nutná,...",True,True,https://goo.gl/forms/DhfY21CiwIasezAY2,,Úvod do programování

In [19]:
"""
Vypíšte celkovú sumu za všetky kurzy
"""
coursesDf["course_price"].sum()

7500

In [20]:
"""
Vypíšte celkovú sumu za kurzy, kde lektorom je Pavel Lasák
"""
coursesDf[coursesDf["couches"] == 'PAVEL LASÁK']["course_price"].sum()

600

In [21]:
"""
Vypíšte celkový počet kurzov, ktoré majú lektora
"""
coursesDf["title"][coursesDf["couches"] != ''].count()

7

In [22]:
"""
Vypíšte minimálnu cenu za kurz
"""
coursesDf.course_price.min()

300

In [23]:
"""
Vypíšte maximálnu cenu za kurz
"""
coursesDf.course_price.max()

2000

In [24]:
"""
Vypíšte TOP 3 najdrahšie kurzy
"""
coursesDf.course_price.sort_values(ascending=False)[:3]

id
54    2000
55    2000
50     500
Name: course_price, dtype: int64

In [25]:
"""
Cez value_counts() za každého lektora vypíšte celkový počet kurzov
"""
coursesDf[coursesDf["couches"] != '']["couches"].value_counts()

PAVEL LASÁK          2
ANNA PASCENKO        1
PAVEL UNGR           1
KUAN-HENG LIN        1
MARTINA VOTRUBOVÁ    1
VLADIMÍR VALOUCH     1
Name: couches, dtype: int64

In [26]:
"""
Zoraďte kurzy podľa titlu vzostupne
"""
coursesDf.sort_values(by="title").head()

,contact_person,couches,course_category,course_description,course_end_date,course_price,course_start_date,course_venue,interested_form_link,max_capacity,notes,open_registration,publish,registration_form_link,repeat,title
id,,,,,,,,,,,,,,,,
66,"{'id': 4, 'user': 'info@czechitas.cz'}",PAVEL LASÁK,"{'id': 11, 'title': 'Exceluju!', 'color_code':...","Máme tady další Excel workshop, protože vás po...",2016-12-03T16:30:00Z,300,2016-12-03T08:00:00Z,"{'id': 3, 'title': 'Fakulta informatiky Masary...",https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,1,Osnova workshopu:\r\n– Základy + pár efektivní...,True,True,https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,,Excel workshop
49,"{'id': 4, 'user': 'info@czechitas.cz'}",PAVEL LASÁK,"{'id': 11, 'title': 'Exceluju!', 'color_code':...",Chceš konečně pochopit Excel?!\r\n \r\nExcel j...,2016-10-22T15:30:00Z,300,2016-10-22T07:00:00Z,"{'id': 4, 'title': 'Kampus', 'street_name': 'P...",https://goo.gl/forms/DhfY21CiwIasezAY2,1,Osnova workshopu:\r\n– Základy + pár efektivní...,True,True,https://goo.gl/forms/DhfY21CiwIasezAY2,,Excel workshop
54,"{'id': 4, 'user': 'info@czechitas.cz'}",VLADIMÍR VALOUCH,"{'id': 2, 'title': 'I can code!', 'color_code'...",Did you know that mobile app development is on...,2016-12-13T20:00:00Z,2000,2016-10-11T16:00:00Z,"{'id': 7, 'title': 'Impact Hub', 'street_name'...",https://goo.gl/forms/DhfY21CiwIasezAY2,1,Prerequisities: Basic knowledge of programming...,True,True,https://goo.gl/forms/DhfY21CiwIasezAY2,,I can code!: Android course
50,"{'id': 4, 'user': 'info@czechitas.cz'}",KUAN-HENG LIN,"{'id': 2, 'title': 'I can code!', 'color_code'...",Czechitas will have course in English! Again! ...,2016-11-15T18:30:00Z,500,2016-10-25T16:00:00Z,"{'id': 5, 'title': 'CERGE-EI', 'street_name': ...",https://goo.gl/forms/DhfY21CiwIasezAY2,1,Prerequisities: The Course is for absolute beg...,True,True,https://goo.gl/forms/DhfY21CiwIasezAY2,every Tuesday,I can code!: Basics of R programming
67,"{'id': 4, 'user': 'info@czechitas.cz'}",ANNA PASCENKO,"{'id': 2, 'title': 'I can code!', 'color_code'...",Have you already implemented any application o...,2016-11-26T16:30:00Z,300,2016-11-26T08:30:00Z,"{'id': 11, 'title': 'Konica Minolta', 'street_...",https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,1,,True,True,https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,,I can code!: Introduction to databases

In [28]:
"""
Zoraďte kurzy podľa ceny vzostupne a podľa dátumu konania zostupne
"""
coursesDf.sort_values(["course_price", "course_start_date"], ascending=[False, True]).head()

,contact_person,couches,course_category,course_description,course_end_date,course_price,course_start_date,course_venue,interested_form_link,max_capacity,notes,open_registration,publish,registration_form_link,repeat,title
id,,,,,,,,,,,,,,,,
55,"{'id': 4, 'user': 'info@czechitas.cz'}",,"{'id': 1, 'title': 'Web development!', 'color_...",​Cílem kurzu je získání praktických zkušeností...,2016-12-14T19:00:00Z,2000,2016-09-21T16:00:00Z,"{'id': 3, 'title': 'Fakulta informatiky Masary...",https://goo.gl/forms/DhfY21CiwIasezAY2,1,PRO KOHO JE KURZ URČEN: Kurz je určen pro dívk...,True,True,https://goo.gl/forms/DhfY21CiwIasezAY2,,Tvořím web: od A do Z!
54,"{'id': 4, 'user': 'info@czechitas.cz'}",VLADIMÍR VALOUCH,"{'id': 2, 'title': 'I can code!', 'color_code'...",Did you know that mobile app development is on...,2016-12-13T20:00:00Z,2000,2016-10-11T16:00:00Z,"{'id': 7, 'title': 'Impact Hub', 'street_name'...",https://goo.gl/forms/DhfY21CiwIasezAY2,1,Prerequisities: Basic knowledge of programming...,True,True,https://goo.gl/forms/DhfY21CiwIasezAY2,,I can code!: Android course
50,"{'id': 4, 'user': 'info@czechitas.cz'}",KUAN-HENG LIN,"{'id': 2, 'title': 'I can code!', 'color_code'...",Czechitas will have course in English! Again! ...,2016-11-15T18:30:00Z,500,2016-10-25T16:00:00Z,"{'id': 5, 'title': 'CERGE-EI', 'street_name': ...",https://goo.gl/forms/DhfY21CiwIasezAY2,1,Prerequisities: The Course is for absolute beg...,True,True,https://goo.gl/forms/DhfY21CiwIasezAY2,every Tuesday,I can code!: Basics of R programming
53,"{'id': 4, 'user': 'info@czechitas.cz'}",,"{'id': 2, 'title': 'I can code!', 'color_code'...","Láká tě programování, ale vůbec nevíš, jak bys...",2016-10-16T15:30:00Z,300,2016-10-16T07:00:00Z,"{'id': 1, 'title': 'Impact Hub', 'street_name'...",https://goo.gl/forms/DhfY21CiwIasezAY2,1,"Co s sebou: Vlastní notebook, myš (není nutná,...",True,True,https://goo.gl/forms/DhfY21CiwIasezAY2,,Úvod do programování
49,"{'id': 4, 'user': 'info@czechitas.cz'}",PAVEL LASÁK,"{'id': 11, 'title': 'Exceluju!', 'color_code':...",Chceš konečně pochopit Excel?!\r\n \r\nExcel j...,2016-10-22T15:30:00Z,300,2016-10-22T07:00:00Z,"{'id': 4, 'title': 'Kampus', 'street_name': 'P...",https://goo.gl/forms/DhfY21CiwIasezAY2,1,Osnova workshopu:\r\n– Základy + pár efektivní...,True,True,https://goo.gl/forms/DhfY21CiwIasezAY2,,Excel workshop

In [31]:
"""
V stĺpci publish a open registration nahradte True za 1 a False za 0 a uložte ako dátový typ int
"""
coursesDf[["publish", "open_registration"]] = coursesDf[["publish", "open_registration"]].astype(np.int)
coursesDf.head()

,contact_person,couches,course_category,course_description,course_end_date,course_price,course_start_date,course_venue,interested_form_link,max_capacity,notes,open_registration,publish,registration_form_link,repeat,title
id,,,,,,,,,,,,,,,,
67,"{'id': 4, 'user': 'info@czechitas.cz'}",ANNA PASCENKO,"{'id': 2, 'title': 'I can code!', 'color_code'...",Have you already implemented any application o...,2016-11-26T16:30:00Z,300,2016-11-26T08:30:00Z,"{'id': 11, 'title': 'Konica Minolta', 'street_...",https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,1,,1,1,https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,,I can code!: Introduction to databases
66,"{'id': 4, 'user': 'info@czechitas.cz'}",PAVEL LASÁK,"{'id': 11, 'title': 'Exceluju!', 'color_code':...","Máme tady další Excel workshop, protože vás po...",2016-12-03T16:30:00Z,300,2016-12-03T08:00:00Z,"{'id': 3, 'title': 'Fakulta informatiky Masary...",https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,1,Osnova workshopu:\r\n– Základy + pár efektivní...,1,1,https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,,Excel workshop
65,"{'id': 4, 'user': 'info@czechitas.cz'}",,"{'id': 2, 'title': 'I can code!', 'color_code'...","Láká tě programování, ale vůbec nevíš, jak bys...",2016-12-03T17:00:00Z,300,2016-12-03T09:00:00Z,"{'id': 1, 'title': 'Impact Hub', 'street_name'...",https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,1,"Vlastní notebook, myš (není nutná, ale bude se...",1,1,https://docs.google.com/forms/d/e/1FAIpQLSfrtC...,,Úvod do programování
58,"{'id': 4, 'user': 'info@czechitas.cz'}",MARTINA VOTRUBOVÁ,"{'id': 13, 'title': 'Jsem digitální', 'color_c...","Sociální sítě dnes používá snad každý, ale víš...",2016-11-23T19:00:00Z,300,2016-11-23T16:00:00Z,"{'id': 5, 'title': 'CERGE-EI', 'street_name': ...",https://goo.gl/forms/DhfY21CiwIasezAY2,1,Blok a tužku a dobrou náladu!,1,1,https://goo.gl/forms/DhfY21CiwIasezAY2,,Jsem digitální!: Sociální sítě
59,"{'id': 4, 'user': 'info@czechitas.cz'}",PAVEL UNGR,"{'id': 13, 'title': 'Jsem digitální', 'color_c...","Nejen programování je člověk živ, a proto ti p...",2016-11-28T20:00:00Z,300,2016-11-28T17:00:00Z,"{'id': 7, 'title': 'Impact Hub', 'street_name'...",https://goo.gl/forms/DhfY21CiwIasezAY2,1,"Vlastní notebook, myš (není nutná, ale bude se...",1,1,https://goo.gl/forms/DhfY21CiwIasezAY2,,Jsem digitální!: SEO interaktivní workshop

In [43]:
courses = coursesDf[coursesDf["couches"] != '']

In [44]:
pivot = pd.pivot_table(courses, index='couches', margins = True, values='course_price', aggfunc='sum')

In [45]:
pivot

                   course_price
couches
ANNA PASCENKO               300
KUAN-HENG LIN               500
MARTINA VOTRUBOVÁ           300
PAVEL LASÁK                 600
PAVEL UNGR                  300
VLADIMÍR VALOUCH           2000
All                        4000

In [75]:
courses.groupby('couches')["couches"].count()

couches
ANNA PASCENKO        1
KUAN-HENG LIN        1
MARTINA VOTRUBOVÁ    1
PAVEL LASÁK          2
PAVEL UNGR           1
VLADIMÍR VALOUCH     1
Name: couches, dtype: int64

In [83]:
courses.groupby(['couches', 'course_start_date'])["course_price"].agg(sum)

couches            course_start_date
ANNA PASCENKO      2016-11-26T08:30:00Z     300
KUAN-HENG LIN      2016-10-25T16:00:00Z     500
MARTINA VOTRUBOVÁ  2016-11-23T16:00:00Z     300
PAVEL LASÁK        2016-10-22T07:00:00Z     300
                   2016-12-03T08:00:00Z     300
PAVEL UNGR         2016-11-28T17:00:00Z     300
VLADIMÍR VALOUCH   2016-10-11T16:00:00Z    2000
Name: course_price, dtype: int64

In [85]:
courses.groupby(['couches', 'course_start_date'])["course_price"].describe()

                                        count    mean  std     min     25%  \
couches           course_start_date
ANNA PASCENKO     2016-11-26T08:30:00Z    1.0   300.0  NaN   300.0   300.0
KUAN-HENG LIN     2016-10-25T16:00:00Z    1.0   500.0  NaN   500.0   500.0
MARTINA VOTRUBOVÁ 2016-11-23T16:00:00Z    1.0   300.0  NaN   300.0   300.0
PAVEL LASÁK       2016-10-22T07:00:00Z    1.0   300.0  NaN   300.0   300.0
                  2016-12-03T08:00:00Z    1.0   300.0  NaN   300.0   300.0
PAVEL UNGR        2016-11-28T17:00:00Z    1.0   300.0  NaN   300.0   300.0
VLADIMÍR VALOUCH  2016-10-11T16:00:00Z    1.0  2000.0  NaN  2000.0  2000.0

                                           50%     75%     max
couches           course_start_date
ANNA PASCENKO     2016-11-26T08:30:00Z   300.0   300.0   300.0
KUAN-HENG LIN     2016-10-25T16:00:00Z   500.0   500.0   500.0
MARTINA VOTRUBOVÁ 2016-11-23T16:00:00Z   300.0   300.0   300.0
PAVEL LASÁK       2016-10-22T07:00:00Z   300.0   300.0   300.0
                  2016-12-03T08:00:00Z   300.0   300.0   300.0
PAVEL UNGR        2016-11-28T17:00:00Z   300.0   300.0   300.0
VLADIMÍR VALOUCH  2016-10-11T16:00:00Z  2000.0  2000.0  2000.0

In [88]:
courses.groupby(['couches', 'course_start_date'])["course_price"].agg(sum).unstack()

course_start_date,2016-10-11T16:00:00Z,2016-10-22T07:00:00Z,2016-10-25T16:00:00Z,2016-11-23T16:00:00Z,2016-11-26T08:30:00Z,2016-11-28T17:00:00Z,2016-12-03T08:00:00Z
couches,,,,,,,
ANNA PASCENKO,NaN,NaN,NaN,NaN,300.0,NaN,NaN
KUAN-HENG LIN,NaN,NaN,500.0,NaN,NaN,NaN,NaN
MARTINA VOTRUBOVÁ,NaN,NaN,NaN,300.0,NaN,NaN,NaN
PAVEL LASÁK,NaN,300.0,NaN,NaN,NaN,NaN,300.0
PAVEL UNGR,NaN,NaN,NaN,NaN,NaN,300.0,NaN
VLADIMÍR VALOUCH,2000.0,NaN,NaN,NaN,NaN,NaN,NaN